name: Mirror and run GitLab CI on PR comment

on:
  issue_comment:
    types: created

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }} && github.event.issue_comment.body == 'begin benchmark'
    runs-on: ubuntu-latest
    steps:
      - name: Mirrror and trigger CI
        uses: actions/checkout@v1
        uses: lutengda/gitlab-mirror-and-ci-action@master
        with:
          args: "http://gitlab.cnosdb.com:8280/root/cnosdb"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "true"
          GITLAB_HOSTNAME: "43.247.178.238:8280"
          GITLAB_USERNAME: "root"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "9"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add benchmark result address
        uses: actions/github-script@v5
        env:
          commit_id: $(git rev-parse --short=7 ${{ github.sha }})
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const comment = 'https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_${{ commit_id }}.html
                https://cnosdb-admin.teleport.cnosdb.com/benchmark-tsbs/tsbs_${{ commit_id }}.html';
              github.pull_request.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.event.issue.number,
                body: comment
              });
